### ISSUE TITLE
bombs out with no usage data

### ISSUE THREAD

**Issue by DanielNagy** [johnf/amber-electric-influxdb#1]
Just signed up to Amber, and I was unable to run this docker image due to no usage data.

GetUsageForHub returns the following json

`{
  "data": null,
  "serviceResponseType": 1,
  "message": "Nmi has not been assigned yet."
}`

The following error is produced

`./amber-electric.rb:39:in `block in run': undefined method `[]' for nil:NilClass (NoMethodError)
        from ./amber-electric.rb:31:in `loop'
        from ./amber-electric.rb:31:in `run'
        from ./amber-electric.rb:133:in `<main>'
`

Currently commented out lines 39 to 41 so the usage data isnt processed. 

Would be good if you incorporate this check into your code

Thanks

**Comment by johnf** [comment]
I've added some code to check for this but can't easily test myself. Could you give it a try?

Thanks

**Comment by DanielNagy** [comment]
Thanks john, I'm unable to test it now, as the usage data now returns the following.. 
`{
  "data": {
    "currentNEMtime": "2020-02-04T21:32:47Z",
    "thisWeekUsage": {},
    "lastWeekUsage": {},
    "lastMonthUsage": {},
    "thisWeekDailyUsage": [],
    "lastWeekDailyUsage": [],
    "lastMonthDailyUsage": [],
    "usageDataTypes": []
  },
  "serviceResponseType": 1,
  "message": null
}`

**Comment by johnf** [comment]
Ahh OK, they must have configured your meter.

I'll close this on the basis it was probably fixed in https://github.com/johnf/amber-electric-influxdb/commit/e2c086433d36fcfef155f369fbcb1fa1c2538125
